# Site settings
title: AberCompSoc
description: >
 Site for the Aberystwyth Computer Science Society

baseurl: ""
url: "http://abercompsoc.github.io"

author:
  fullname: AberCompSoc
  #googleplus: https://www.google.com/+
  github: abercompsoc
  twitter: abercompsoc

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
